### ISSUE TITLE
SLP>>Devanagari

### ISSUE THREAD

**Issue by Shalu411** [funderburkjim/hitopadesha-kale#2]
Namaste
Wow! This is super work- very timely and needed for my classes. How did you know that I am gonna work with this :)?
I have been working with a Hindi edition of Hitopadesha, a translation from a  different author.
Now I needed English and I get it! Happy to have it. 
One request is that- the files where the "source text matter is above and translation below", (Samskrt and English - one above the other) I need the source text n Devanagari with English translation retained. Presently Samskrt text is in SLP1
Second request is that- the whole SLP1 "Only source text" into Devanagari.
Thanks a lot for the work.
-Shubhamastu (May the auspicious happen)

**Comment by Shalu411** [comment]
@funderburkjim 
Namaste
Any update on this?

**Comment by funderburkjim** [comment]
@Shalu411   Hi!  

Here is a review of what has been done so far.  It is a work in progress.

There is now digitization of 
*  The Hitopadesha itself: [hitopadesha-slp1.txt](https://github.com/funderburkjim/hitopadesha-kale/blob/master/hitopadesha-slp1/hitopadesha-slp1.txt)
* Kale's 'Notes' chapter at back of book.  There is a file for each of these pages, e.g.
   [Page 1 of notes](https://github.com/funderburkjim/hitopadesha-kale/blob/master/hitonotes/notes/hitonote_001_ocr_Sam.txt)
* The 'marma-prakASa' notes at the bottom of each page of the text, such as 
  [page 1 mp](https://github.com/funderburkjim/hitopadesha-kale/blob/master/hitopadesha-slp1/sam-hito-p/sampada_mp_001.txt)
* Kale's [English translation](https://github.com/funderburkjim/hitopadesha-kale/blob/master/hitoenglish/hitoeng.txt)

Sampada helped with much of this.

What I am currently working on is aligning the MP and English with the text;
this is [hitokale_slp1_p.txt](https://github.com/funderburkjim/hitopadesha-kale/blob/master/hitopadesha-slp1/hitokale_slp1_p.txt).  This also involves splitting
the English into sections that correspond to a small number of lines of the text.
Currently this alignment process is at about page 45.

**Comment by funderburkjim** [comment]
> Request for Devanagari.  

Should be able to do that.

Glad someone might find this work of use.

**Comment by funderburkjim** [comment]
## Two Devanagari versions

* [hitokale_deva_p.txt](https://github.com/funderburkjim/hitopadesha-kale/blob/master/hitopadesha-slp1/deva/hitokale_deva_p.txt)
* [hitopadesha-deva.txt](https://github.com/funderburkjim/hitopadesha-kale/blob/master/hitopadesha-slp1/deva/hitopadesha-deva.txt)

@Shalu411   Are these what you have in mind?

**Comment by Shalu411** [comment]
Hariom
This text will do! It is more than what is asked for! 
I am blessed to have this help.
We can close this

**Comment by funderburkjim** [comment]
Glad it helped!
